---
- name: Pull SciCalculator Docker Image
  hosts: localhost
  gather_facts: no  # Disables unnecessary fact gathering
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub
      command: docker login -u vaibhav48 -p vaibhav123456789

    - name: Pull the latest SciCalculator image
      command: docker pull vaibhav48/calculatorfinaltest

    - name: Stop and remove existing container (if running)
      command: docker rm -f scicalculator
      ignore_errors: yes  # Prevents failure if the container doesn't exist

    - name: Run the SciCalculator container in detached mode
      command: docker run -it -d --name scicalculator vaibhav48/calculator:latest
