---
- name: Deploy SciCalculator Docker Container
  hosts: localhost
  become: true  # Run as sudo (required for Docker)

  tasks:
    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Pull the latest SciCalculator image
      community.docker.docker_image:
        name: vaibhav48/calculatortest
        source: pull
        force_source: true

    - name: Remove existing container (if running)
      community.docker.docker_container:
        name: scicalculator
        state: absent  # Stops and removes the container if it exists

    - name: Run the SciCalculator container
      community.docker.docker_container:
        name: scicalculatortest
        image: vaibhav48/calculatortest # Change if needed
        state: started
        restart_policy: always
        detach: false  # Keeps the container running in foreground
