---
- name: Deploy SciCalculator Docker Container
  hosts: localhost
  become: true  # Run as sudo (required for Docker)
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub (Workaround)
      command: docker login -u {{ docker_hub_username }} -p {{ docker_hub_password }}

    - name: Pull the latest SciCalculator image (Workaround)
      command: docker pull vaibhav48/calculator:latest

    - name: Stop and remove existing container (if running)
      command: docker rm -f scicalculator
      ignore_errors: yes  # Ignore errors if the container is not running

    - name: Run the SciCalculator container (Workaround)
      command: docker run --name scicalculator -d --restart always vaibhav48/calculator:latest
