---
- name: Deploy SciCalculator Docker Container
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub
      docker_login:
        username: "{{ docker_hub_username }}"
        password: "{{ docker_hub_password }}"

    - name: Pull the latest SciCalculator image
      docker_image:
        name: vaibhav48/calculator:latest  # Update with your actual image
        source: pull
        state: present

    - name: Remove existing container (if running)
      docker_container:
        name: scicalculator
        state: absent

    - name: Run the SciCalculator container
      docker_container:
        name: scicalculator
        image: vaibhav48/calculator:latest  # Update if necessary
        state: started
        restart_policy: always
        detach: true  # Keep it running in the background
