---
- name: Pull SciCalculator Docker Image
  hosts: localhost
  gather_facts: no  # Disables unnecessary fact gathering
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub
      command: docker login -u {{ docker_hub_username }} -p {{ docker_hub_password }}

    - name: Pull the latest SciCalculator image
      command: docker pull vaibhav48/calculator:latest
