---
- name: Deploy SciCalculator Docker Container
  hosts: localhost
  gather_facts: no  # 🔹 Disables fact gathering that requires sudo
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Log in to Docker Hub
      command: docker login -u {{ docker_hub_username }} -p {{ docker_hub_password }}

    - name: Pull the latest SciCalculator image
      command: docker pull vaibhav48/calculator:latest

    - name: Stop and remove existing container (if running)
      command: docker rm -f scicalculator
      ignore_errors: yes
      
    - name: Run the SciCalculator container in interactive mode
      command: docker run --name scicalculator -it vaibhav48/calculator:latest
